do (angular) ->
  angular.module('help').factory 'helpStore', ->
    layoutMenu: 'This is the layout menu. You can select a layout or import yours in the data tab. In the other tabs, you can design what should look like the layout circle.'
    min: 'min/max: the range of the plot axis, data outside this range are clipped. If you do not specify the axis range using min/max values, then the axis will be scaled to span the full range of the data.'
    max: 'min/max: the range of the plot axis, data outside this range are clipped. If you do not specify the axis range using min/max values, then the axis will be scaled to span the full range of the data.'
    interpolation: 'how points are linked to each others'
    linear: 'piecewise linear segments, as in a polyline'
    basis: 'a B-spline, with control point duplication on the ends'
    cardinal: 'a Cardinal spline, with control point duplication on the ends'
    monotone: 'cubic interpolation that preserves monotonicity in y'
    rules: 'Rules allow you to define specific values according to datum characteristics'
    layout: 'Control the circular axis layout'
    newTrack: 'Add data to your image'
    editTrack: 'Edit the data on your image'
    svg: 'Vector image format to save all information about your Circos image'
    png: 'Save a screenshot of your Circos image'
    html: 'To embed on your website and be able to visualize animations. Ask for it in the feedback form'
    share: 'Propose this layout (and its configuration) to appear in the librairy of layouts'
    shareDetails: 'describe the layout, the source of the data or other information for the moderator'
    share2: 'You can share layouts and tracks that other users might be interested to use. Once accepted, it will appear on the select box in the data tab.'
    trackDataPrefix: 'One data point per line. Each data point property should be separated by a space or tab or comma etc. e.g.:\n'
